# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
# SPDX-FileCopyrightText: 2026 spatterlight
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: Check existence of GitLab Runner systemd service
  ansible.builtin.stat:
    path: "{{ devture_systemd_docker_base_systemd_path }}/{{ gitlab_runner_identifier }}.service"
  register: gitlab_runner_service_stat

- name: Uninstall GitLab Runner systemd services and files
  when: gitlab_runner_service_stat.stat.exists | bool
  block:
    - name: Ensure GitLab Runner systemd service is stopped
      ansible.builtin.service:
        name: "{{ gitlab_runner_identifier }}"
        state: stopped
        enabled: false
        daemon_reload: true

    - name: Ensure GitLab Runner systemd service does not exist
      ansible.builtin.file:
        path: "{{ devture_systemd_docker_base_systemd_path }}/{{ gitlab_runner_identifier }}.service"
        state: absent

    - name: Ensure GitLab Runner container network does not exist
      when: gitlab_runner_container_network_deletion_enabled
      block:
        - name: Ensure GitLab Runner container network does not exist via community.docker.docker_network
          when: devture_systemd_docker_base_container_network_creation_method == 'ansible-module'
          community.docker.docker_network:
            name: "{{ gitlab_runner_container_network }}"
            state: absent

        - name: Ensure GitLab Runner container network does not exist via ansible.builtin.command
          when: devture_systemd_docker_base_container_network_creation_method == 'command'
          ansible.builtin.command:
            cmd: >-
              {{ devture_systemd_docker_base_host_command_docker }} network rm
              {{ gitlab_runner_container_network }}
          register: gitlab_runner_network_deletion_result
          changed_when: gitlab_runner_container_network in gitlab_runner_network_deletion_result.stdout

# Everything in here is generated (by this role, or by GitLab Runner itself), so there is no data to keep.
# The runners stay registered in GitLab, and can be deleted there.
- name: Ensure GitLab Runner paths do not exist
  ansible.builtin.file:
    path: "{{ gitlab_runner_base_path }}"
    state: absent
